# Generated by Django 5.0.6 on 2024-09-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_coach_player_team_delete_message_player_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
